#!/usr/bin/env bash
# DEV_ENV_HOME=~/dotfiles # this one is for copying the config files and folders 

if [ -z "$DEV_ENV_HOME" ]; then
    log "ENV var DEV_ENV_HOME needs to be present"
    exit 1
fi

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "--------- dev-env ---------"

cd $script_dir

# Copy directory from dotfiles to root 
copy_dir() {
    pushd $1
    to=$2
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd
}

# Copy file from dotfiles to root 
copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $to/$name
    execute cp $from $to/$name
}

# In this case it will seach for .config in dotfiles and copy everything inside it into xdghome
log "#--------------CONFIG FOLDERS--------------#"
copy_dir $DEV_ENV_HOME/.config $XDG_CONFIG_HOME


log "#-----------------BINARIES-----------------#"
copy_file $DEV_ENV_HOME/run $HOME/.local/bin
copy_file $DEV_ENV_HOME/dev-env $HOME/.local/bin
copy_file $DEV_ENV_HOME/tmux/tmux-sessionizer $HOME/.local/bin
copy_file $DEV_ENV_HOME/tmux/ready-tmux $HOME/.local/bin


log "#---------------CONFIG FILES---------------#"
copy_file $DEV_ENV_HOME/git/.gitconfig $HOME
copy_file $DEV_ENV_HOME/git/.githelpers $HOME
copy_file $DEV_ENV_HOME/.zshrc $HOME
